export default [
  "Giesing, München",
  "Hauptbahnhof, München",
  "Karlsplatz (Stachus), München",
  "Moosach, München",
  "Ostbahnhof München, München",
  "Fraunhoferstraße, München",
  "Hohenzollernplatz, München",
  "Max-Weber-Platz, München",
  "Münchner Freiheit, München",
  "Petuelring, München",
  "Rotkreuzplatz, München",
  "Scheidplatz, München",
  "Sendlinger Tor, München",
  "Silberhornstraße, München",
  "Westendstraße, München",
  "Westfriedhof, München",
  "Feldmoching, München",
  "Harras, München",
  "Heimeranplatz, München",
  "Marienplatz, München",
  "Neuperlach Süd, München",
  "Trudering, München",
  "Berg am Laim, München",
  "Isartor, München",
  "Pasing, München",
  "Rosenheimer Platz, München",
  "Kreillerstraße, München",
  "Lehel, München",
  "Stiglmaierplatz, München",
  "Wettersteinplatz, München",
  "Aidenbachstraße, München",
  "Alte Heide, München",
  "Am Hart, München",
  "Arabellapark, München",
  "Brudermühlstraße, München",
  "Böhmerwaldplatz, München",
  "Candidplatz, München",
  "Dietlindenstraße, München",
  "Dülferstraße, München",
  "Forstenrieder Allee, München",
  "Frankfurter Ring, München",
  "Fürstenried West, München",
  "Garching, Garching (b München)",
  "Garching, Forschungszentrum, Garching (b München)",
  "Garching-Hochbrück, Garching (b München)",
  "Georg-Brauchle-Ring, München",
  "Giselastraße, München",
  "Goetheplatz, München",
  "Großhadern, München",
  "Haderner Stern, München",
  "Harthof, München",
  "Hasenbergl, München",
  "Holzapfelkreuth, München",
  "Implerstraße, München",
  "Josephsburg, München",
  "Josephsplatz, München",
  "Karl-Preis-Platz, München",
  "Kieferngarten, München",
  "Klinikum Großhadern, München",
  "Kolumbusplatz, München",
  "Königsplatz, München",
  "Laimer Platz, München",
  "Machtlfinger Straße, München",
  "Maillingerstraße, München",
  "Mangfallplatz, München",
  "Messestadt Ost, München",
  "Messestadt West, München",
  "Michaelibad, München",
  "Milbertshofen, München",
  "Moosacher St.-Martins-Platz, München",
  "Neuperlach Zentrum, München",
  "Nordfriedhof, München",
  "Obersendling, München",
  "Oberwiesenfeld, München",
  "Odeonsplatz, München",
  "Olympia-Einkaufszentrum, München",
  "Olympiazentrum, München",
  "Partnachplatz, München",
  "Poccistraße, München",
  "Prinzregentenplatz, München",
  "Quiddestraße, München",
  "Richard-Strauss-Straße, München",
  "Schwanthalerhöhe, München",
  "St.-Quirin-Platz, München",
  "Studentenstadt, München",
  "Thalkirchen (Tierpark), München",
  "Universität, München",
  "Westpark, München",
  "Hackerbrücke, München",
  "Agnes-Bernauer-Straße, München",
  "Albrechtstraße, München",
  "Am Knie, München",
  "Am Lokschuppen, München",
  "Amalienburgstraße, München",
  "Ammerseestraße, München",
  "Ampfingstraße, München",
  "Arabellapark/Klinikum Bogenhausen, München",
  "Arabellastraße, München",
  "Barbarastraße, München",
  "Baumkirchner Straße, München",
  "Botanischer Garten, München",
  "Chiemgaustraße, München",
  "Cosimabad, München",
  "Dall'Armistraße, München",
  "Derbolfinger Platz, Grünwald (Kr München)",
  "Domagkstraße, München",
  "Donnersbergerstraße, München",
  "Effnerplatz, München",
  "Einsteinstraße, München",
  "Fasaneriestraße, München",
  "Flurstraße, München",
  "Friedensengel/Villa Stuck, München",
  "Fritz-Meyer-Weg, München",
  "Fürstenrieder Straße, München",
  "Grillparzerstraße, München",
  "Haidenauplatz, München",
  "Hans-Thonauer-Straße, München",
  "Hauptbahnhof Nord, München",
  "Herkomerplatz, München",
  "Hochschule München (Lothstr.), München",
  "Holzkirchner Bahnhof, München",
  "Infanteriestraße, München",
  "Klinikum Harlaching, München",
  "Kurfürstenplatz, München",
  "Lautensackstraße, München",
  "Leonrodplatz, München",
  "Lohensteinstraße, München",
  "Maria-Ward-Straße, München",
  "Mariahilfplatz, München",
  "Mauerkircherstraße, München",
  "Max-Weber-Platz (Johannispl.), München",
  "Nationalmuseum/Haus der Kunst, München",
  "Nordbad, München",
  "Offenbachstraße, München",
  "Ostfriedhof, München",
  "Parzivalplatz, München",
  "Pinakotheken, München",
  "Potsdamer Straße, München",
  "Prinz-Eugen-Park, München",
  "Rathaus Pasing, München",
  "Regerplatz, München",
  "Regina-Ullmann-Straße, München",
  "Riedenburger Straße, München",
  "Romanplatz, München",
  "Schellingstraße, München",
  "Schloss Nymphenburg, München",
  "Schlösselgarten, München",
  "Schlüsselbergstraße, München",
  "Schwabing Nord, München",
  "Schwanseestraße, München",
  "Siglstraße, München",
  "St. Emmeram, München",
  "St.-Veit-Straße, München",
  "Steubenplatz, München",
  "Taimerhofstraße, München",
  "Tegernseer Landstraße, München",
  "Tivolistraße, München",
  "Trappentreustraße, München",
  "Vogelweideplatz, München",
  "Werinherstraße, München",
  "Westbad, München",
  "Wintrichring, München",
  "Allach, München",
  "Aubing, München",
  "Deisenhofen, Deisenhofen (b München)",
  "Donnersbergerbrücke, München",
  "Fasanenpark, Fasanenpark (b München)",
  "Fasanerie, München",
  "Fasangarten, München",
  "Feldkirchen, Feldkirchen (b München)",
  "Flughafen, Besucherpark, München",
  "Freiham, München",
  "Furth, Furth (b München)",
  "Grafing Bahnhof, Grafing (b München)",
  "Grafing Stadt, Grafing (b München)",
  "Gronsdorf, Gronsdorf (b München)",
  "Haar, Haar (b München)",
  "Hirschgarten, München",
  "Johanneskirchen, München",
  "Laim, München",
  "Langwied, München",
  "Lochhausen, München",
  "Lohhof, Lohhof (Kr München)",
  "Neuaubing, München",
  "Obermenzing, München",
  "Perlach, München",
  "Riem, München",
  "Siemenswerke, München",
  "Solln, München",
  "Taufkirchen, Taufkirchen (b München)",
  "Untermenzing, München",
  "Westkreuz, München",
  "Basler Straße, München",
  "Bonner Platz, München",
  "Freimann, München",
  "Friedenheimer Straße, München",
  "Fröttmaning, München",
  "Gern, München",
  "Innsbrucker Ring, München",
  "Moosfeld, München",
  "Therese-Giehse-Allee, München",
  "Theresienstraße, München",
  "Theresienwiese, München",
  "Untersbergstraße, München",
  "Ackermannstraße, München",
  "Agnes-Bernauer-Platz, München",
  "Am Gasteig, München",
  "Am Münchner Tor, München",
  "Anni-Albers-Straße, München",
  "Authariplatz, München",
  "Barthstraße, München",
  "Bavariafilmplatz, Grünwald (Kr München)",
  "Borstei, München",
  "Briefzentrum, München",
  "Bundesfinanzhof, München",
  "Burghausener Straße, München",
  "Clemensstraße, München",
  "Deroystraße, München",
  "Deutsches Museum, München",
  "Eduard-Schmid-Straße, München",
  "Elisabethplatz, München",
  "Fachnerstraße, München",
  "Gartenstraße, München",
  "Gondrellplatz, München",
  "Großhesseloher Brücke, München",
  "Hanauer Straße, München",
  "Hauptbahnhof Süd, München",
  "Heideckstraße, München",
  "Hermann-Lingg-Straße, München",
  "Herzogstraße, München",
  "Hochschule München, München",
  "Holbeinstraße, München",
  "Holzapfelstraße, München",
  "Hopfenstraße, München",
  "Hubertusstraße, München",
  "Hugo-Troendle-Straße, München",
  "Kammerspiele, München",
  "Karl-Theodor-Straße, München",
  "Karlstraße, München",
  "Karolinenplatz, München",
  "Kriemhildenstraße, München",
  "Kurzstraße, München",
  "Lenbachplatz, München",
  "Ludwig-Thoma-Straße, Grünwald (Kr München)",
  "Mariannenplatz, München",
  "Marienplatz (Theatinerstraße), München",
  "Marsstraße, München",
  "Maximilianeum, München",
  "Maxmonument, München",
  "Menterschwaige, München",
  "Mutschellestraße, München",
  "Müllerstraße, München",
  "Nationaltheater, München",
  "Neuhausen, München",
  "Nordendstraße, München",
  "Olympiapark West, München",
  "Ottostraße, München",
  "Paradiesstraße, München",
  "Parkplatz, Grünwald (Kr München)",
  "Pelkovenstraße, München",
  "Reichenbachplatz, München",
  "Renatastraße, München",
  "Robert-Koch-Straße, Grünwald (Kr München)",
  "Sandstraße, München",
  "Schilcherweg, München",
  "Schrenkstraße, München",
  "Schwabinger Tor, München",
  "Senftenauerstraße, München",
  "St.-Martins-Platz, München",
  "Stadtwerke München, München",
  "Stegener Weg, München",
  "Sternwartstraße, München",
  "Säulingstraße, München",
  "Südtiroler Straße, München",
  "Theodolindenplatz, München",
  "Tiroler Platz, München",
  "Volkartstraße, München",
  "Wiener Platz, München",
  "Willibaldplatz, München",
  "Wörthstraße, München",
  "Daglfing, München",
  "Eichenau, Eichenau (b München)",
  "Englschalking, München",
  "Flughafen München, München",
  "Leienfelsstraße, München",
  "Leuchtenbergring, München",
  "Mittersendling, München",
  "St.-Martin-Straße, München",
  "Aberlestraße, München",
  "Abt-Petto-Straße, Deisenhofen (b München)",
  "Abtstraße, München",
  "Abzw. Gudrunsiedlung, Brunnthal (b München)",
  "Abzw. Waldbrunn, Brunnthal (b München)",
  "Achatstraße, München",
  "Ackermannbogen, München",
  "Adilostraße, München",
  "Adunistraße, München",
  "Aichacher Straße, München",
  "Aindorferstraße, München",
  "Akazienstraße, Taufkirchen (b München)",
  "Allach Bf. Ost, München",
  "Allacher Forstweg, München",
  "Allescherstraße, München",
  "Allgäuer Straße, München",
  "Allinger Straße, München",
  "Alois-Hahn-Weg, München",
  "Alte Allee, München",
  "Altenburgstraße, München",
  "Alter Messeplatz, München",
  "Altöttinger Straße, München",
  "Am Blütenanger, München",
  "Am Brunnen, Kirchheim (b München)",
  "Am Durchblick, München",
  "Am Eichbüchl, Eichenau (b München)",
  "Am Gries, Furth (b München)",
  "Am Haderner Winkel, Neuried (Kr München)",
  "Am Hain, München",
  "Am Harras, München",
  "Am Hart Süd, München",
  "Am Hedernfeld, München",
  "Am Hedernfeld Nord, München",
  "Am Hochacker, München",
  "Am Messesee, München",
  "Am See, Haar (b München)",
  "Am Tucherpark, München",
  "Am Ährenfeld, München",
  "Amalienstraße, München",
  "Ammerseestraße, Neuried (Kr München)",
  "Amphionpark, München",
  "Amsterdamer Straße, München",
  "An der Point, München",
  "Andernacher Straße, München",
  "Andreas-Vöst-Straße, München",
  "Angererstraße, München",
  "Angerlohstraße, München",
  "Anhalter Platz, München",
  "Annelies-Kupper-Allee, Haar (b München)",
  "Anton-Ditt-Bogen, München",
  "Anton-Will-Straße, München",
  "Anzinger Straße, München",
  "Appenzeller Straße, München",
  "Arabellapark Nord, München",
  "Arcisstraße, München",
  "Aschenbrennerstraße, München",
  "Aschheimer Straße, München",
  "Asmarstraße, München",
  "Astallerstraße, München",
  "Auenbruggerstraße, München",
  "Auerfeldstraße, München",
  "Auf der Wies, Furth (b München)",
  "Augustenfelder Straße, München",
  "Augustenstraße, München",
  "Augustin-Rösch-Straße, München",
  "Aurbacherstraße, München",
  "Aurikelstraße, München",
  "Autharistraße, München",
  "Auweg, Garching (b München)",
  "Avenariusplatz, München",
  "BMW-FIZ, München",
  "Baaderstraße, München",
  "Bad Forstenried, München",
  "Bad Maria Einsiedel, München",
  "Bad-Schachener-Straße, München",
  "Bahnhofstraße, Dornach (b München)",
  "Bahnhofstraße, Taufkirchen (b München)",
  "Bahnhofstraße, Eichenau (b München)",
  "Bahnstraße, München",
  "Baierbrunner Straße, München",
  "Bajuwarenstraße, München",
  "Balanstraße, München",
  "Baldeplatz, München",
  "Barlachstraße, München",
  "Bastian-Schmid-Platz, München",
  "Batschkastraße, München",
  "Baubergerstraße, München",
  "Baumgartnerstraße, München",
  "Baumkirchner Platz, München",
  "Bauseweinallee, München",
  "Bayerischer Rundfunk, München",
  "Bayerwaldstraße, München",
  "Beethovenplatz, München",
  "Bellinzonastraße, München",
  "Benderstraße, München",
  "Benedikterstraße, München",
  "Berduxstraße, München",
  "Berg am Laim Bf. (Süd), München",
  "Berger-Kreuz-Straße, München",
  "Bergerwaldstraße, München",
  "Bergmannstraße, München",
  "Bergsonstraße, München",
  "Bergstraße, Brunnthal (b München)",
  "Bergstraße, Deisenhofen (b München)",
  "Bergstraße, Grafing (b München)",
  "Bergwachtstraße, München",
  "Bernheimerstraße, München",
  "Bernsteinweg, München",
  "Bertha-von-Suttner-Weg, München",
  "Betschartstraße, München",
  "Bichlhofweg, München",
  "Bingener Straße, München",
  "Birkhahnweg, München",
  "Bismarckstraße, München",
  "Bleibtreustraße, München",
  "Blumenau, München",
  "Blumenstraße, München",
  "Blutenburg, München",
  "Boltzmannstraße, Garching (b München)",
  "Boschbrücke, München",
  "Bremer Straße, München",
  "Breslauer Straße, Garching (b München)",
  "Brunnenweg, Garching (b München)",
  "Brunnthal, Ort, Brunnthal (b München)",
  "Bruno-Walter-Ring, München",
  "Buchenstraße, Lohhof (Kr München)",
  "Bunzlauer Platz, München",
  "Burgauerstraße, München",
  "Bürgerhaus, Dornach (b München)",
  "Bürgerhaus, Garching (b München)",
  "Bürgerhaus, Haar (b München)",
  "Bürgerpark Oberföhring, München",
  "Campingplatz Langwieder See, München",
  "Campingplatz Obermenzing, München",
  "Campingplatz Thalkirchen, München",
  "Caracciolastraße, München",
  "Carl-Orff-Straße, Eichenau (b München)",
  "Carola-Neher-Straße, München",
  "Chinesischer Turm, München",
  "Cincinnatistraße, München",
  "Clarita-Bernhard-Straße, München",
  "Claude-Lorrain-Straße, München",
  "Claudiusplatz, München",
  "Corinthstraße, München",
  "Corneliusbrücke, München",
  "Curd-Jürgens-Straße, München",
  "Curt-Mezger-Platz, München",
  "Dachstraße, München",
  "Daglfing Bahnhof Ost, München",
  "Daglfing Bahnhof West, München",
  "Daimlerstraße, Garching (b München)",
  "Dankwartstraße, München",
  "Daphnestraße, München",
  "Deidesheimer Straße, München",
  "Denninger Straße, München",
  "Dessauerstraße, München",
  "Detmoldstraße, München",
  "Diakon-Kerolt-Weg, München",
  "Diefenbachstraße, München",
  "Dientzenhoferstraße, München",
  "Dieselstraße, Kirchheim (b München)",
  "Dillinger Straße, München",
  "Dobelklause, Grafing (b München)",
  "Dom-Pedro-Straße, München",
  "Domagkstraße West, München",
  "Donauwörther Straße, München",
  "Dorfstraße, München",
  "Dornacher Straße, Feldkirchen (b München)",
  "Dr.-Rehm-Straße, Neuried (Kr München)",
  "Drachenseestraße, München",
  "Drosselweg, München",
  "Drozzaweg, München",
  "Drygalski-Allee, München",
  "Eberlestraße, München",
  "Edeltraudstraße, München",
  "Edmund-Rumpler-Straße, München",
  "Effnerstraße, München",
  "Ehrenbreitsteiner Straße, München",
  "Ehrenbürgstraße, München",
  "Ehrengutstraße, München",
  "Ehrenmal, München",
  "Eichelhäherstraße, München",
  "Eichenau Nord, Eichenau (b München)",
  "Eichenau Süd, Eichenau (b München)",
  "Eichenstraße, Taufkirchen (b München)",
  "Eininger Straße, München",
  "Einsteinring Nord, Dornach (b München)",
  "Einsteinring Süd, Dornach (b München)",
  "Einsteinring West, Dornach (b München)",
  "Eisendorf, Eisendorf (Grafing b München)",
  "Elektrastraße, München",
  "Elisabeth-Jost-Straße, München",
  "Elisenstraße, München",
  "Ellis-Kaut-Straße, München",
  "Elsenheimerstraße, München",
  "Emdenstraße, München",
  "Emeranstraße, Feldkirchen (b München)",
  "Emmerigweg, München",
  "Engelbertstraße, München",
  "Englburgstraße, München",
  "Englschalkinger Straße, München",
  "Erdinger Landstraße, Dornach (b München)",
  "Erlbachstraße, München",
  "Eschenrieder Straße, München",
  "Eschenstraße, Taufkirchen (b München)",
  "Esmarchstraße, München",
  "Ettalstraße, München",
  "Eugen-Sänger-Ring, Brunnthal (b München)",
  "Eulenspiegelstraße, München",
  "Euro-Industriepark Nord, München",
  "Euro-Industriepark West, München",
  "Evangelische Kirche, Grafing (b München)",
  "Eversbuschstraße, München",
  "F.-Kobell-Str./Waldfriedhof, Haar (b München)",
  "Faganastraße, München",
  "Falkenweg, Neuried (Kr München)",
  "Fasanenstraße, München",
  "Fasangartenstraße, München",
  "Federseestraße, München",
  "Feldbergstraße, München",
  "Feldmoching Bf. Ost, München",
  "Feldmochinger Anger, München",
  "Feldmochinger See, München",
  "Feldstraße, Lohhof (Kr München)",
  "Ferchenbachstraße, München",
  "Fernpaßstraße, München",
  "Fertigstraße, München",
  "Fichtenstraße, Neuried (Kr München)",
  "Finkenweg, Lohhof (Kr München)",
  "Finsterwalderstraße, München",
  "Fischer-von-Erlach-Straße, München",
  "Flemischweg, München",
  "Fliederstraße, Neuried (Kr München)",
  "Florastraße, München",
  "Floriansmühlstraße, München",
  "Floßlände, München",
  "Flughafen, AirSite 43, München",
  "Flughafen, Briefzentrum, München",
  "Flughafen, MAC/Terminal 1, München-Flughafen",
  "Flughafen, Parkpl. P41/Novotel, München-Flughafen",
  "Flughafen, Terminal 2, München-Flughafen",
  "Flughafen, Terminalbereich A/B, München-Flughafen",
  "Flughafen, Terminalbereich D/E, München-Flughafen",
  "Flößergasse, München",
  "Fockensteinstraße, München",
  "Forst-Kasten-Allee, München",
  "Forstenried, München",
  "Forstenrieder Park, München",
  "Franz-Nißl-Straße, München",
  "Franz-Sperr-Weg, München",
  "Frasdorfer Straße, München",
  "Frauendorferstraße, München",
  "Frauenmantelanger, München",
  "Freibadstraße, Haar (b München)",
  "Freiham Möbel Höffner, München",
  "Freiligrathstraße, München",
  "Freimanner Hölzl, München",
  "Freischützstraße, München",
  "Friedastraße, München",
  "Friedenskirche, Eichenau (b München)",
  "Friedenspromenade, München",
  "Friedhof, Taufkirchen (b München)",
  "Friedhof, Grünwald (Kr München)",
  "Friedhof Obermenzing, München",
  "Friedhof Perlach, München",
  "Friedhof Riem, München",
  "Friedhof Untermenzing, München",
  "Friedrich-Eckart-Straße, München",
  "Friedrich-Engels-Bogen, München",
  "Friedrich-Hebbel-Straße, München",
  "Friedrich-Schüle-Straße, Feldkirchen (b München)",
  "Friedrichstraße, München",
  "Friesplatz, München",
  "Fröttmaning Auensiedlung, München",
  "Fuggerstraße, München",
  "Gaiglstraße, München",
  "Galileiplatz, München",
  "Ganghoferbrücke, München",
  "Garmischer Straße, München",
  "Gautinger Straße, München",
  "Geisenhausenerstraße, München",
  "Gelbhofstraße, München",
  "Gellertstraße, München",
  "Georg-Birk-Straße, München",
  "Georg-Brauchle-Haus, München",
  "Georg-Hirth-Platz, München",
  "Georg-Reismüller-Straße, München",
  "Georgenstraße, München",
  "Geretsrieder Straße, München",
  "Gerhardstraße, München",
  "Gerlachweg, München",
  "Germeringer Weg, München",
  "Gertrud-Grunow-Straße, München",
  "Gewerbegebiet, Garching (b München)",
  "Gewerbegebiet, Eichenau (b München)",
  "Gewerbegebiet Süd, Feldkirchen (b München)",
  "Gilchinger Straße, München",
  "Gilgstraße, München",
  "Glötzleweg, München",
  "Gmunder Straße, München",
  "Gnadenwaldplatz, München",
  "Goethering, Grafing (b München)",
  "Goldberg, Grafing (b München)",
  "Goldlackplatz, München",
  "Gollierplatz, München",
  "Goteboldstraße, München",
  "Gotzinger Platz, München",
  "Graf-Lehndorff-Straße, München",
  "Graf-Zeppelin-Platz, Garching (b München)",
  "Grafinger Straße, München",
  "Grashofstraße, München",
  "Griechenstraße, München",
  "Griegstraße, München",
  "Griesstraße, Grafing (b München)",
  "Grimmeisenstraße, München",
  "Großhaderner Straße, München",
  "Großlappen, München",
  "Großmarkthalle, München",
  "Gruithuisenstraße, München",
  "Grusonstraße, München",
  "Gräfelfinger Straße, München",
  "Gröbenzeller Straße, München",
  "Grünstraße, München",
  "Grüntal, München",
  "Gudrunsiedlung, Brunnthal (b München)",
  "Guido-Schneble-Straße, München",
  "Gulbranssonstraße, München",
  "Gundelkoferstraße, München",
  "Gundermannstraße, München",
  "Gustav-Freytag-Straße, München",
  "Gustav-Mahler-Straße, München",
  "Gutenbergstraße, Garching (b München)",
  "Gymnasium, Kirchheim (b München)",
  "Gymnasium, Haar (b München)",
  "Gymnasium, Grünwald (Kr München)",
  "Gymnasium, Grafing (b München)",
  "Gärtnerplatztheater, München",
  "Gärtnerstraße, München",
  "Görresstraße, München",
  "Görzer Straße, München",
  "Görzer Straße Schule, München",
  "Haderunstraße, München",
  "Haidlinger Weg, Grafing (b München)",
  "Haidstraße, Brunnthal (b München)",
  "Haimhauser Straße, Lohhof (Kr München)",
  "Hainbuchenring, Neuried (Kr München)",
  "Hainbuchenstraße, Taufkirchen (b München)",
  "Halfinger Straße, München",
  "Halligenplatz, München",
  "Hanebergstraße, München",
  "Hanna-Kirchner-Weg, München",
  "Hans-Fischer-Straße, München",
  "Hans-Steinkohl-Straße, München",
  "Hans-Stießberger-Str. (Schleife), Haar (b München)",
  "Hans-Stießberger-Straße, Haar (b München)",
  "Hansapark, München",
  "Hansastraße, München",
  "Hasenbergl Süd, München",
  "Hasenberglstraße, München",
  "Hatzelweg, München",
  "Hauptschule, Kirchheim (b München)",
  "Hauptstraße, Eichenau (b München)",
  "Hauseggerstraße, München",
  "Hausen, Kirchheim (b München)",
  "Hauzenberger Straße, München",
  "Haylerstraße, München",
  "Hechtseestraße, München",
  "Heckenstallerstraße, München",
  "Heckscherstraße, München",
  "Hedwigstraße, Lohhof (Kr München)",
  "Heerstraße, München",
  "Heerstraße West, München",
  "Heidemannstraße, München",
  "Heimeranplatz Süd, München",
  "Heimgartenstraße, Lohhof (Kr München)",
  "Heinrich-Wieland-Straße, München",
  "Hellensteinstraße, München",
  "Helsinkistraße, München",
  "Heltauer Straße, München",
  "Herbststraße, Eichenau (b München)",
  "Hermann-Gmeiner-Weg, München",
  "Hermann-Pünder-Straße, München",
  "Herthastraße, München",
  "Herzog-Ernst-Platz, München",
  "Herzogen Wege, Kirchheim (b München)",
  "Herzogpark, München",
  "Himalajastraße, München",
  "Himmelschlüsselstraße, München",
  "Hinterbrühl, München",
  "Hinterbärenbadstraße, München",
  "Hippelstraße, München",
  "Hirschauer Straße, München",
  "Hirschgartenallee, München",
  "Hirtenweg, Grünwald (Kr München)",
  "Hochäckerstraße, München",
  "Hofangerstraße, München",
  "Hofbrunnstraße, München",
  "Hofbräuallee, München",
  "Hofmannstraße, München",
  "Hofmarkstraße, Deisenhofen (b München)",
  "Hohensteinstraße, München",
  "Hohenzollernstraße, München",
  "Holzwiesenstraße, München",
  "Hortigstraße, München",
  "Hubertusbrunnen, München",
  "Hubertusplatz, Deisenhofen (b München)",
  "Hufelandstraße, München",
  "Hugo-Junkers-Straße, Taufkirchen (b München)",
  "Hugo-Lang-Bogen, München",
  "Humboldtstraße, München",
  "Humboldtstraße, Dornach (b München)",
  "Höcherstraße, München",
  "Höglwörther Straße, München",
  "Hönigschmidplatz, München",
  "IAK-Klinikum München-Ost, Haar (b München)",
  "Ikea, Taufkirchen (b München)",
  "Ilse-Fehling-Straße, München",
  "Iltisstraße, München",
  "Im Gefilde, München",
  "Im Wismat, München",
  "In den Kirschen, München",
  "Infanteriestraße Süd, München",
  "Ingolstädter Straße, München",
  "Irisstraße, München",
  "Isarbrücke, Grünwald (Kr München)",
  "Isarring, München",
  "Isartor/Zweibrückenstraße, München",
  "Isengaustraße, München",
  "Ittlingerstraße, München",
  "Jagdfeldbad, Haar (b München)",
  "Jagdfeldzentrum, Haar (b München)",
  "Jagdhornstraße, München",
  "Jahnstraße, Feldkirchen (b München)",
  "Jahnstraße, Grafing (b München)",
  "Jakob-Gelb-Platz, München",
  "Jakob-Kaiser-Straße, München",
  "Jaspersallee, München",
  "Joh.-Seb.-Bach-Straße, Haar (b München)",
  "Johann-Clanze-Straße, München",
  "Johann-Schmid-Straße, Lohhof (Kr München)",
  "Johanneskirchen Bf. West, München",
  "Johanneskirchner Straße, München",
  "Josef-Frankl-Straße, München",
  "Josef-Lang-Straße, München",
  "Josef-Sammer-Straße, Grünwald (Kr München)",
  "Josef-Wirth-Weg, München",
  "Josefstraße, Deisenhofen (b München)",
  "Joseph-Dollinger-Bogen, München",
  "Joseph-Suder-Bogen, München",
  "Josephinenstraße, München",
  "Kafkastraße, München",
  "Kaiserhölzlstraße, München",
  "Kapellenstraße, Feldkirchen (b München)",
  "Kapuzinerplatz/Arbeitsagentur, München",
  "Kapuzinerstraße, München",
  "Karl-Hammerschmidt-Straße, Dornach (b München)",
  "Karl-Hänel-Straße, München",
  "Karl-Marx-Ring, München",
  "Karl-Schmid-Straße, München",
  "Karl-von-Roth-Straße, München",
  "Karlsfelder Straße, München",
  "Karwinskistraße Ost, München",
  "Karwinskistraße West, München",
  "Kastenbauerstraße, München",
  "Kazmairstraße, München",
  "Keilberthstraße, München",
  "Keltenring, Taufkirchen (b München)",
  "Keltenweg, Garching (b München)",
  "Kemnatenstraße, München",
  "Kemptener Straße, München",
  "Kiebitzstraße, Lohhof (Kr München)",
  "Kiefernstraße, München",
  "Kirche, Gronsdorf (b München)",
  "Kirchenstraße, München",
  "Kirchtruderinger Straße, München",
  "Kirschenstraße, Taufkirchen (b München)",
  "Kistlerhofstraße, München",
  "Klagenfurter Straße, München",
  "Klara-Ziegler-Bogen, München",
  "Klenzestraße, München",
  "Kleselstraße, München",
  "Klinikum Großhadern Nord, München",
  "Klinikum Großhadern Ost, München",
  "Klinikum Neuperlach, München",
  "Klopstockstraße, München",
  "Knappertsbuschstraße, München",
  "Knorrstraße, München",
  "Kollwitzstraße, München",
  "Kolumbusplatz (Nord), München",
  "Kolumbusplatz/Humboldtstraße, München",
  "Korbinian-Beer-Straße, München",
  "Korbinianplatz, München",
  "Kornwegerstraße, München",
  "Kraillinger Weg, München",
  "Kraillinger Weg, Neuried (Kr München)",
  "Krankenhaus Martha Maria, München",
  "Krankenhaus Pasing, München",
  "Krauss-Maffei-Straße, München",
  "Krauss-Maffei-Straße Ost, München",
  "Krautheimstraße, München",
  "Kriegelsteinerstraße, München",
  "Kriegerdenkmal, Taufkirchen (b München)",
  "Kristallstraße, München",
  "Krokusstraße, München",
  "Kronstadter Straße, München",
  "Kronwinkler Straße, München",
  "Krumbadstraße, München",
  "Krähenweg, München",
  "Kuckucksblumenstraße, München",
  "Kufsteiner Platz, München",
  "Kulturzentrum Trudering, München",
  "Kunihohstraße, München",
  "Kunreuthstraße, München",
  "Kunstmannstraße, München",
  "Kurparkstraße, München",
  "Kustermannpark, München",
  "Kölner Platz, München",
  "Königinstraße, München",
  "Lagerhausstraße, München",
  "Lamprechtstraße, München",
  "Landrichterstraße, München",
  "Landshuter Allee, München",
  "Langbürgener Straße, München",
  "Langwied Ortsmitte, München",
  "Langwieder See, München",
  "Lassallestraße, München",
  "Laubenweg, Neuried (Kr München)",
  "Lauinger Straße, München",
  "Lebscheestraße, München",
  "Lehrer-Stieglitz-Straße, Garching (b München)",
  "Lehrer-Wirth-Straße, München",
  "Leibstraße, Haar (b München)",
  "Leifstraße, München",
  "Leonhardikirche, Grafing (b München)",
  "Lerchenauer See, München",
  "Lerchenauer Straße, München",
  "Lerchenstraße, München",
  "Leutstettener Straße, München",
  "Liebigstraße, Kirchheim (b München)",
  "Lilienthalallee Süd, München",
  "Lilienthalstraße, Garching (b München)",
  "Lilienthalstraße, Taufkirchen (b München)",
  "Limesstraße, München",
  "Limmatstraße, München",
  "Lincolnstraße, München",
  "Lindberghstraße, München",
  "Lindenviertel, Kirchheim (b München)",
  "Lochhausener Straße, München",
  "Lohengrinstraße, München",
  "Lohhof Bf. Nord, Lohhof (Kr München)",
  "Lohhof Bf. Süd, Lohhof (Kr München)",
  "Lorettoplatz, München",
  "Lotte-Branz-Straße, München",
  "Ludmillastraße, München",
  "Ludwig-Erhard-Allee, München",
  "Ludwig-Linsert-Straße, München",
  "Ludwig-Moser-Straße, Haar (b München)",
  "Ludwig-Prandtl-Straße, Garching (b München)",
  "Ludwig-Thoma-Straße, Deisenhofen (b München)",
  "Ludwigsbrücke, München",
  "Ludwigsfeld (Campingplatz), München",
  "Luise-Kiesselbach-Platz, München",
  "Luisenstraße, München",
  "Lustheimstraße, München",
  "Lärchenweg/Volkshochschule, Taufkirchen (b München)",
  "Lübecker Straße, München",
  "Lüneburger Straße, München",
  "MAN, Siedlung, München",
  "MVG-Museum, München",
  "Mahirstraße, München",
  "Maier-Leibnitz-Straße, Garching (b München)",
  "Mainaustraße, München",
  "Maistraße, München",
  "Mallertshofener Straße, Lohhof (Kr München)",
  "Mangfallplatz Süd, München",
  "Mangfallstraße, Neuried (Kr München)",
  "Manzostraße, München",
  "Marchioninistraße, München",
  "Margarete-Steiff-Straße, München",
  "Margaretenanger, Lohhof (Kr München)",
  "Margaretenplatz, München",
  "Margaretha-Ley-Ring, Dornach (b München)",
  "Margot-Kalinke-Straße, München",
  "Maria-Eich-Straße, München",
  "Maria-Einsiedel-Straße, München",
  "Maria-Probst-Straße, München",
  "Mariabrunner Straße, München",
  "Marienburger Straße, München",
  "Marienplatz (Rindermarkt), München",
  "Marienstern, München",
  "Markgrafenstraße, München",
  "Marschnerstraße, München",
  "Marsopstraße, München",
  "Martin-Empl-Ring, München",
  "Matterhornstraße, München",
  "Max-Bill-Straße, München",
  "Max-Born-Straße, München",
  "Max-Diamand-Straße, München",
  "Max-Lebsche-Platz, München",
  "Max-Wönner-Straße, München",
  "Maxhofstraße, München",
  "Maxhofweg, Neuried (Kr München)",
  "Maxvorstadt/Sammlung Brandhorst, München",
  "Meisenstraße, Eichenau (b München)",
  "Melchiorstraße, München",
  "Memeler Straße, München",
  "Menaristraße, München",
  "Menterstraße, München",
  "Merseburger Straße, München",
  "Mettenstraße, München",
  "Milbertshofener Platz, München",
  "Milbertshofener Straße, München",
  "Mildred-Scheel-Bogen, München",
  "Mindelheimer Straße, München",
  "Minnewitstraße, München",
  "Mitterfeldstraße, München",
  "Mitterweg, München",
  "Moosacher Straße, München",
  "Moosfeld Gewerbegebiet, München",
  "Moselstraße, München",
  "Mozartstraße, Feldkirchen (b München)",
  "Munckerstraße, München",
  "Murnauer Straße, München",
  "Muspillistraße, München",
  "Mutter-Teresa-Straße, München",
  "Mönchbergstraße, München",
  "Mühldorfstraße, München",
  "Mühlenstraße, Grafing (b München)",
  "Mühlgasse, Garching (b München)",
  "Münchener Straße, Lanzenhaar",
  "Münchener Straße, Erding",
  "Münchener Straße, Neufarn (Vaterstetten)",
  "Münchener Straße, Planegg",
  "Münchener Straße, Germering",
  "Münchener Straße, Kleinberghofen (Kr Dachau)",
  "Münchener Straße, Hilgertshausen",
  "Münchner Straße, Feldkirchen (b München)",
  "Münsinger Straße, München",
  "Nailastraße, München",
  "Nauestraße, München",
  "Nawiaskystraße, München",
  "Nederlinger Straße, München",
  "Nederlinger Straße (West), München",
  "Nelkenstraße, Lohhof (Kr München)",
  "Nesselwanger Straße, München",
  "Nettelbeckstraße, München",
  "Netzerstraße, München",
  "Neuaubing West, München",
  "Neuer Friedhof, Neuried (Kr München)",
  "Neuer Südfriedhof, München",
  "Neuer Südfriedhof West, München",
  "Neufahrn (Lkr.München), Neufahrn (Schäftlarn)",
  "Neuherbergstraße, München",
  "Neuhofen, München",
  "Neumarkter Straße, München",
  "Neunkirchner Straße, München",
  "Neurieder Straße, München",
  "Nikolaus-Prugger-Weg, München",
  "Nusselstraße, München",
  "Nymphenburg Süd, München",
  "Oberföhring Post, München",
  "Oberhofer Platz, München",
  "Oberhofer Weg, München",
  "Obernzeller Straße, München",
  "Oberweg, Taufkirchen (b München)",
  "Odinpark, München",
  "Odinstraße, München",
  "Ohlauer Straße, München",
  "Ohmstraße, Dornach (b München)",
  "Olschewskibogen, München",
  "Olympia-Einkaufszentrum Ost, München",
  "Olympia-Einkaufszentrum West, München",
  "Olympia-Pressestadt, München",
  "Olympiaberg, München",
  "Olympiapark Eissportstadion, München",
  "Olympiapark Nord, München",
  "Olympiasee, München",
  "Olympiastraße, Feldkirchen (b München)",
  "Opalstraße, München",
  "Orleansstraße, München",
  "Orthstraße, München",
  "Ortlerstraße, München",
  "Oskar-Maria-Graf-Ring, München",
  "Oskar-von-Miller-Ring, München",
  "Ostbahnhof (Bildungszentrum), München",
  "Ostbahnhof (Post), München",
  "Ostbahnhof Friedenstraße, München",
  "Osterangerstraße, München",
  "Osterwaldstraße, München",
  "Ostpark Eislaufzentrum, München",
  "Ottilienstraße, München",
  "Otto-Hahn-Ring, München",
  "Otto-Hahn-Straße, Dornach (b München)",
  "Otto-Warburg-Straße, München",
  "Paidarstraße, München",
  "Pappelallee, München",
  "Paracelsusstraße, München",
  "Parkring Süd, Garching (b München)",
  "Parkring West, Garching (b München)",
  "Parkstadt Solln, München",
  "Pasing Bf. Nord, München",
  "Pasinger Heuweg, München",
  "Pasinger Marienplatz, München",
  "Paul-Gerhardt-Allee, München",
  "Paul-Henri-Spaak-Straße, München",
  "Paul-Hindemith-Allee, München",
  "Paul-Wassermann-Straße, München",
  "Paulaner Brauerei, München",
  "Perlschneiderstraße, München",
  "Peschelanger, München",
  "Peslmüllerstraße, München",
  "Peter-Anders-Straße, München",
  "Peter-Auzinger-Straße, München",
  "Pfanzeltplatz, München",
  "Pfarrer-Grimm-Straße, München",
  "Pfarrer-Huber-Straße, Eichenau (b München)",
  "Pfr.-Caspar-Mayr-Platz, Kirchheim (b München)",
  "Phantasiestraße, München",
  "Pienzenauer Straße, Grafing (b München)",
  "Pilsenseestraße, München",
  "Pirolstraße, München",
  "Planegger Straße, München",
  "Plankenfelser Straße, München",
  "Plassenburgstraße, München",
  "Platanenstraße, München",
  "Platanenstraße, Taufkirchen (b München)",
  "Plattlinger Straße, München",
  "Plettstraße, München",
  "Polkostraße, München",
  "Poschingerstraße, München",
  "Posener Platz, München",
  "Pregerstraße, München",
  "Preußenstraße, München",
  "Priel, München",
  "Prof.-Angermair-Ring, Garching (b München)",
  "Pronnerplatz, München",
  "Pulverturm, München",
  "Pulverturmstraße, München",
  "Putzbrunner Straße, München",
  "Pöllatstraße, München",
  "Pörtschacher Straße, München",
  "Pühnstraße, München",
  "Pündterplatz, München",
  "Raiffeisenstraße, Lohhof (Kr München)",
  "Ramersdorf, München",
  "Rangierbahnhof, München",
  "Rappelhofstraße, München",
  "Rathaus, Kirchheim (b München)",
  "Rathaus, Taufkirchen (b München)",
  "Rathaus, Grünwald (Kr München)",
  "Rathaus, Neuried (Kr München)",
  "Rathaus, Feldkirchen (b München)",
  "Rathenaustraße, München",
  "Ratzingerplatz, München",
  "Ravensburger Ring, München",
  "Realschule, Taufkirchen (b München)",
  "Rechnerstraße, Haar (b München)",
  "Redwitzstraße, München",
  "Reginbaldstraße, München",
  "Reitmorstraße/Sammlung Schack, München",
  "Rennbahnstraße, München",
  "Ridlerstraße, München",
  "Riederstraße, München",
  "Riem, Dornach, Dornach (b München)",
  "Riesenburgstraße, München",
  "Riesstraße, München",
  "Riesstraße Süd, München",
  "Rindermarkt, München",
  "Ringelnatzweg, München",
  "Robinienstraße, München",
  "Rockefellerstraße, München",
  "Roecklplatz, München",
  "Rofanstraße, München",
  "Roggensteiner Allee, Eichenau (b München)",
  "Rose-Pichler-Weg, München",
  "Rotter Straße, Grafing (b München)",
  "Rubensstraße, München",
  "Rudolf-Gütlein-Straße, Haar (b München)",
  "Rudolf-Zorn-Straße, München",
  "Rueßstraße, München",
  "Rupert-Mayer-Straße, München",
  "Ruth-Schaumann-Straße, München",
  "Röblingweg, München",
  "Römerhofweg, Garching (b München)",
  "Rümannstraße, München",
  "Rümelinstraße, München",
  "Saalburgstraße, München",
  "Sadelerstraße, München",
  "Salzmannstraße, München",
  "Sanftlring, Grafing (b München)",
  "Sankt Michael, München",
  "Sankt Pius, München",
  "Sankt-Konrad-Straße, Haar (b München)",
  "Sapporobogen, München",
  "Sarasatestraße, München",
  "Scapinellistraße, München",
  "Schatzbogen, München",
  "Scheidplatz Süd, München",
  "Schichtlstraße, München",
  "Schilfstraße, Eichenau (b München)",
  "Schillerstraße, Eichenau (b München)",
  "Schittgablerstraße, München",
  "Schleißheimer Kanal, Garching (b München)",
  "Schloss Blutenburg, München",
  "Schlörstraße, München",
  "Schmaedelstraße, München",
  "Schmuckerweg, München",
  "Schneemannstraße, München",
  "Schopenhauerstraße, München",
  "Schragenhofstraße, München",
  "Schulstraße, Eichenau (b München)",
  "Schulzentrum, Lohhof (Kr München)",
  "Schumacherring, München",
  "Schwankhardtweg, München",
  "Schwarzhölzlstraße, München",
  "Schwarzwaldstraße, München",
  "Schweigerstraße, München",
  "Schwester-Eubulina-Platz, München",
  "Schäftlarnstraße, München",
  "Schäufeleinstraße, München",
  "Seeholzenweg, München",
  "Selma-Lagerlöf-Straße, München",
  "Sendlinger Kirche, München",
  "Senserstraße, München",
  "Servetstraße, München",
  "Siedlung Ludwigsfeld, München",
  "Siedlung am Haidelweg, München",
  "Siedlung am Hart, München",
  "Siegenburger Straße, München",
  "Siegfried-Mollier-Straße, München",
  "Siegmannstraße, München",
  "Siemensallee, München",
  "Sigmund-Riefler-Bogen, München",
  "Silberdistelstraße, München",
  "Silberhorn-/Ichostraße, München",
  "Simplonstraße, München",
  "Sipplinger Straße, München",
  "Situlistraße, München",
  "Skagerrakstraße, München",
  "Sofienstraße, Gronsdorf (b München)",
  "Solln Bf. Wendeschleife, München",
  "Sollner Straße, München",
  "Sondermeierstraße, München",
  "Sonnentaustraße, München",
  "Soyerhofstraße, München",
  "Spechtstraße, Eichenau (b München)",
  "Sperberstraße, München",
  "Spertentalstraße, München",
  "Spielmannsauer Straße, München",
  "Spindlerplatz, München",
  "Spiridon-Louis-Ring, München",
  "Spixstraße, München",
  "Sportpark, Lohhof (Kr München)",
  "St. Korbinian, Lohhof (Kr München)",
  "St.-Augustinus-Straße, München",
  "St.-Cajetan-Straße, München",
  "St.-Georg-Straße, Brunnthal (b München)",
  "St.-Jakobs-Platz, München",
  "St.-Johann-Straße, München",
  "St.-Martin-Straße Ost, München",
  "St.-Rita-Weg, Deisenhofen (b München)",
  "Stadelheimer Straße, München",
  "Staffelseestraße, München",
  "Stahlgruberring, München",
  "Stanigplatz, München",
  "Starnberger Weg, Neuried (Kr München)",
  "Staudingerstraße, München",
  "Staufener Straße, München",
  "Stegmühlstraße, München",
  "Steinerstraße, München",
  "Steirerstraße, München",
  "Stephansplatz, München",
  "Stettiner Weg, Garching (b München)",
  "Stettnerstraße, München",
  "Stiftsbogen, München",
  "Stridbeckstraße, München",
  "Stroblstraße, München",
  "Stäblistraße, München",
  "Ständlerstraße, München",
  "Stösserstraße, München",
  "Stücklenstraße, München",
  "Sudermannallee, München",
  "Sudetendeutsche Straße, München",
  "Sumpfmeisenweg, München",
  "Sylvensteinstraße, München",
  "Säbener Straße, München",
  "Südliche Ingolstädter Straße, Lohhof (Kr München)",
  "Südpark, München",
  "Süskindstraße, München",
  "Tal, München",
  "Taubenstraße, München",
  "Technische Universität, München",
  "Technische Universität, Garching (b München)",
  "Tegernseer Landstraße, Taufkirchen (b München)",
  "Terofalstraße, München",
  "Tessiner Straße, München",
  "Tettnanger Straße, München",
  "Theodolindenstraße, München",
  "Theresienhöhe, München",
  "Thiemestraße, München",
  "Thomas-Dehler-Straße, München",
  "Thomas-Hauser-Straße, München",
  "Thomasiusplatz, München",
  "Thuillestraße, München",
  "Tierheim, München",
  "Tierpark (Alemannenstraße), München",
  "Tischlerstraße, München",
  "Togostraße, München",
  "Toni-Merkens-Weg, München",
  "Trabrennbahn, München",
  "Traunsteiner Straße, München",
  "Trenkleweg, München",
  "Tribulaunstraße, München",
  "Truchthari-Anger, München",
  "Truderinger Straße, München",
  "Truderinger Straße, Brücke, München",
  "Tubeufstraße, München",
  "Tumblingerstraße, München",
  "Turnerstraße, München",
  "Tölzer Straße, München",
  "Türkenstraße, München",
  "Ubostraße, München",
  "Umschlagbahnhof, München",
  "Ungsteiner Straße, München",
  "Untere Länge, München",
  "Untere Strassäcker, Garching (b München)",
  "Untermenzinger Straße, München",
  "Ursberger Straße, München",
  "Valeppstraße, München",
  "Varnhagenstraße, München",
  "Veldener Straße, München",
  "Veldensteinstraße, München",
  "Vesaliusstraße, München",
  "Viktualienmarkt, München",
  "Vinzenz-Schüpfer-Straße, München",
  "Vockestraße, Haar (b München)",
  "Vogelloh, München",
  "Vogesenstraße, München",
  "Volkartstraße Ost, München",
  "Vollmannstraße, München",
  "Volmstraße, München",
  "Von-Braunmühl-Straße, Haar (b München)",
  "Von-Erckert-Straße, München",
  "Von-Kahr-Straße, München",
  "Von-Reuter-Straße, München",
  "Von-der-Tann-Straße, München",
  "Wahnfriedallee, München",
  "Waldfriedhof, München",
  "Waldfriedhof, Lohhof (Kr München)",
  "Waldfriedhof (Wendeschleife), München",
  "Waldfriedhof Haupteingang, München",
  "Waldfriedhof Solln, München",
  "Waldhauserstraße, Neuried (Kr München)",
  "Waldheimplatz, München",
  "Waldhornstraße, München",
  "Waldhüterstraße, München",
  "Waldperlach, München",
  "Waldperlach (Süd), München",
  "Waldstraße, Haar (b München)",
  "Wallnerstraße, München",
  "Waltherstraße, München",
  "Warthestraße, München",
  "Wasserburger Landstraße, München",
  "Wasserburger Straße, Haar (b München)",
  "Wasserturmstraße, Garching (b München)",
  "Wastl-Witt-Straße, München",
  "Watzmannring, Garching (b München)",
  "Weddigenstraße, München",
  "Wehnerstraße, München",
  "Wehrlestraße, München",
  "Weidener Straße, München",
  "Weidenstraße, Eichenau (b München)",
  "Weinbergerstraße, München",
  "Weitlstraße, München",
  "Weltistraße, München",
  "Werdenfelsstraße, München",
  "Werner-Egk-Bogen, München",
  "Wertheimer Straße, München",
  "Westerlandanger, München",
  "Weyprechtstraße, München",
  "Whistlerweg, München",
  "Wiesenstraße, Eichenau (b München)",
  "Wiesentfelser Straße, München",
  "Wildanger, München",
  "Wilhelm-Busch-Straße, München",
  "Wilhelm-Dieß-Weg, München",
  "Wilhelm-Hale-Straße, München",
  "Wilhelm-Hertz-Straße, München",
  "Wilhelm-Hoegner-Straße, München",
  "Wilhelm-Kuhnert-Straße, München",
  "Willi-Wien-Straße, München",
  "Willibaldstraße, München",
  "Willy-Messerschmitt-Str., Taufkirchen (b München)",
  "Winfriedstraße, München",
  "Winterstraße, München",
  "Winthirplatz, München",
  "Winzererstraße, München",
  "Woferlstraße, München",
  "Wolframstraße, München",
  "Wolfratshauser Straße, München",
  "Wolkerweg, München",
  "Wöhlerstraße, München",
  "ZOB, München",
  "Zamdorf Siedlung, München",
  "Zamdorfer Straße, München",
  "Zamilapark, München",
  "Zauberwaldstraße, München",
  "Zaubzerstraße, München",
  "Zaunerstraße, München",
  "Zaunweg, München",
  "Zenettistraße, München",
  "Zentralländstraße, München",
  "Zeppelinstraße, Garching (b München)",
  "Zeppelinstraße, Feldkirchen (b München)",
  "Ziegeleistraße, München",
  "Zielstattstraße, München",
  "Zinckgrafstraße, München",
  "Zoppoter Straße, München",
  "Zugspitzstraße, Neuried (Kr München)",
  "Zusestraße, Brunnthal (b München)",
  "Zöllerstraße, München",
  "Züricher Straße, München",
  "Überlinger Weg, München",
  "München Hbf, München",
];
